[package]
name = "aoc-2019-rust"
version = "0.0.1"
authors = ["Ari V <dev@ariari.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
